#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ kailicen@170.187.240.110:/var/www/kailicen.com/
echo "Deployment complete"
